### ISSUE TITLE
Treat all non-serialized skills as not-refundable?

### ISSUE THREAD

**Issue by Darxo** [Battle-Modders/Dynamic-Perks-Framework#16]
The perks are added and removed via stack (`mod_stack_based_skills`) so it should be fine. Even if the bro already had the perk before picking Professional, Professional will add a "stack" of that perk, and when removed will only remove that stack. Meanwhile, if the bro "unlearns" that perk, he will unlearn the original perk, but the stack based addition from Professional will remain.

An issue here can happen with regards to refundability of the perks. So the original perk was refundable, but the one added by Professional isn't - however, the way stack based skills mod works is that the data is kept from the serialized version of the skill. So after the original perk is unlearned, the one added by Professional will also be refundable. I think a meaningful solution to this should be that all non-serialized skills should be considered not-refundable by default. I can update Dynamic Perks Framework to account for this.

_Originally posted by @LordMidas in https://github.com/Battle-Modders/mod-reforged/pull/301#discussion_r1563599728_

**Comment by LordMidas** [comment]
This has been implemented.
